[project]
name = "qr-code-recognizier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anton Shiryaev", email = "med.phisiker@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.3.0",
    "pyzbar>=0.1.9",
]

[project.scripts]
qr-code-recognizier = "qr_code_recognizier:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
